// <auto-generated />
using System;
using CooperGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CooperGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251002032523_Primera")]
    partial class Primera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CooperGame.Models.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJugador"));

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdJugador");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("CooperGame.Models.Partida", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartida"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.Property<DateTime>("TiempoTotal")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPartida");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("CooperGame.Models.Recurso", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecurso"));

                    b.Property<int>("CantidadRecolectada")
                        .HasColumnType("int");

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdRecurso");

                    b.HasIndex("IdPartida");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Registro", b =>
                {
                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("IdJugador", "IdPartida", "Tipo");

                    b.HasIndex("IdPartida");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("CooperGame.Models.Recurso", b =>
                {
                    b.HasOne("CooperGame.Models.Partida", "Partida")
                        .WithMany("Recursos")
                        .HasForeignKey("IdPartida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Registro", b =>
                {
                    b.HasOne("CooperGame.Models.Jugador", "Jugador")
                        .WithMany("Registros")
                        .HasForeignKey("IdJugador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CooperGame.Models.Partida", "Partida")
                        .WithMany("Registros")
                        .HasForeignKey("IdPartida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CooperGame.Models.Jugador", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("CooperGame.Models.Partida", b =>
                {
                    b.Navigation("Recursos");

                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
